### ISSUE TITLE
トグルではない動作にしたい

### ISSUE THREAD

**Issue by alexspringgit** [IndoorCorgi/cgpmgr#1]
RPZ-PowerMGR基板のESWとGNDを短絡すると電源ON/OFFが切り替わりますが、
ESW - GND = 3.3V で電源ON
ESW - GND = 0V で電源OFF
のようにできますか？

現在は、
ESW - GND = 0V で電源ON/OFF切替
というトグル動作になっています。

**Comment by IndoorCorgi** [comment]
電源ON/OFFの切り替えは基板側のコントローラーに書き込まれているプログラム(ファームウェア)で制御しているため、cgpmgrからは変更できません。カスタムファームウェアの開発は有償で承っております。公式サイトの[お問い合わせ](https://www.indoorcorgielec.com/%e3%81%8a%e5%95%8f%e3%81%84%e5%90%88%e3%82%8f%e3%81%9b/)よりご相談下さい。

**Comment by alexspringgit** [comment]
分かりました。
お知らせいただきありがとうございました。
