### ISSUE TITLE
Kernel Panic Every connect to the power management

### ISSUE THREAD

**Issue by mayaaarahayu1** [IndoorCorgi/cgpmgr#2]
Dear developer, i'm using raspberry pi zero that connect with Power Management Indoor Corgi RPZ-PowerMGR Rev.1.1 . 
But everytime the raspberry pi connect to the power management, it cause a kernel error like my screenshot below..
Do you know how to solve it?
![WhatsApp Image 2024-01-31 at 11 15 25 AM](https://github.com/IndoorCorgi/cgpmgr/assets/133184583/5f312ef9-4d60-49fe-8789-3775e6492a30)

**Comment by IndoorCorgi** [comment]
Installing cgpmgr does not affect raspberry pi kernel. Your raspberry pi boots fine without the RPZ-PowerMGR expansion board, but when you connect the RPZ-PowerMGR, does it cause a kernel panic? 

Double check if conifg.txt is modified correctly following to the [usage](https://www.indoorcorgielec.com/products/rpz-powermgr/#%E3%82%BB%E3%83%83%E3%83%88%E3%82%A2%E3%83%83%E3%83%97Raspberry_Pi). 

If the problem still persists, some kind of defect is suspected on the product. Please contact technical support tech@indoorcorgielec.com) or the store where you purchased it to replace with new one.
